import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        Math: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        RegExp: 'readonly',
        Date: 'readonly',
        JSON: 'readonly',
        Promise: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLLabelElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        WebGLRenderer: 'readonly',
        Scene: 'readonly',
        Camera: 'readonly',
        Vector3: 'readonly',
        BufferGeometry: 'readonly',
        BufferAttribute: 'readonly',
        PointsMaterial: 'readonly',
        Points: 'readonly',
        Color: 'readonly',
        // Project globals
        formatResult: 'writable',
        calculateN: 'writable',
        getScenario: 'writable',
        initChart: 'writable',
        updateChart: 'writable',
        defaultValues: 'writable',
        presets: 'writable',
        uncertaintyLevels: 'writable',
        MOBILE_BREAKPOINT: 'writable',
        renderTimeline: 'writable',
        renderKeyConceptsCards: 'writable',
        updateResultDetails: 'writable',
        updateMagnitudeScale: 'writable',
        currentN: 'writable',
        animateValue: 'writable',
        updateGalaxyVisualization: 'writable',
        interpretResult: 'writable',
        galaxyControls: 'writable',
        galaxyRendererFS: 'writable',
        initGalaxySimulation: 'writable',
        getStellarPopulationColor: 'writable',
        updateGalaxyRotation: 'writable',
        updateGalaxyTilt: 'writable',
        updateGalaxyZoom: 'writable',
        updateGalaxyStarSize: 'writable',
        resetGalaxyView: 'writable',
        toggleGalaxyFullscreen: 'writable',
        applyPresetFromFullscreen: 'writable',
        updateParamFromFullscreen: 'writable',
        categoryMap: 'writable',
        updateValueAndRecalculate: 'writable',
        translations: 'writable',
        currentLang: 'writable',
        t: 'writable',
        resetForm: 'writable',
        THREE: 'readonly',
        Chart: 'readonly'
      }
    },
    rules: {
      'no-unused-vars': 'off',
      'no-console': 'off',
      'no-undef': 'off' // Desactivado porque usamos globals
    }
  }
];